feature/W83-1879 - Add Arabic feeds for Google
wecre8-ecommerce/saleor-product-feeds-plugin pull request #3
Opened 2023-03-16 09:52 UTC by IslamMesha

:point_right: Add Arabic feeds for Google

2023-03-16 11:31 UTC, Ashraf-Khaled-BE requested changes
As you know we have no unit test, so please attach a sample of the output of this PR as a review of the test you have done, also please rename the PR to be 
ticket number:  4-7 words explanation of what is done

2023-03-20 08:13 UTC, HazemKhaled requested changes

2023-03-20 08:13 UTC, HazemKhaled commented on productfeeds/plugin.py
> +        "google_feed_url_en": {
don't hardcode the languages

2023-03-21 01:45 UTC, essam5 approved these changes

2023-03-21 07:57 UTC, Ashraf-Khaled-BE approved these changes

2023-03-22 08:17 UTC, HazemKhaled requested changes

2023-03-22 08:17 UTC, HazemKhaled commented on productfeeds/tasks.py
> +def generate_google_feed_csv_file_ar():
Repeated code here should be one task generating files depending on language config

2023-03-26 10:37 UTC, HazemKhaled approved these changes

2023-03-26 10:37 UTC, merged